development:
  #uri: mongodb://heroku_app3468819:hu4bnaljk65jffd6dfjp4uuk84@ds031637.mongolab.com:31637/heroku_app3468819 #dev
  host: localhost
  database: playlist_beta_development

test:
  host: localhost
  database: playlist_beta_test

production:
  uri: <%= ENV['MONGOLAB_URI'] %>